version: "3"
services:
  db:
    image: "postgres:12.3"
    ports:
      - 5432:5432
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: currency_converter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  my_dbdata: